//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolMasterWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CameraID {
            get {
                return ((string)(this["CameraID"]));
            }
            set {
                this["CameraID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MicrophoneID {
            get {
                return ((string)(this["MicrophoneID"]));
            }
            set {
                this["MicrophoneID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ProtocolMasterWPF.Model.ExtensionMetaSetting DriverMeta {
            get {
                return ((global::ProtocolMasterWPF.Model.ExtensionMetaSetting)(this["DriverMeta"]));
            }
            set {
                this["DriverMeta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ProtocolMasterWPF.Model.ExtensionMetaSetting InterpreterMeta {
            get {
                return ((global::ProtocolMasterWPF.Model.ExtensionMetaSetting)(this["InterpreterMeta"]));
            }
            set {
                this["InterpreterMeta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExperimentDefaultTab {
            get {
                return ((string)(this["ExperimentDefaultTab"]));
            }
            set {
                this["ExperimentDefaultTab"] = value;
            }
        }
    }
}
